/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health check */
    get: operations['GetHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/scenes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all scenes */
    get: operations['ListScenes']
    put?: never
    /** Create a new scene */
    post: operations['CreateScene']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/scenes/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    /** Get a scene by ID */
    get: operations['GetScene']
    /** Update a scene */
    put: operations['UpdateScene']
    post?: never
    /** Delete a scene */
    delete: operations['DeleteScene']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    HealthResponse: {
      /** @example ok */
      status: string
    }
    SceneSummary: {
      /** @description Unique identifier (UUID) */
      id: string
      /** @description Human-readable scene name */
      name: string
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
    }
    Scene: components['schemas']['SceneSummary'] & {
      data: components['schemas']['SceneData']
    }
    SceneInput: {
      /** @description Human-readable scene name */
      name: string
      data: components['schemas']['SceneData']
    }
    /** @description Scene content as stored by the frontend */
    SceneData: {
      /**
       * @description Snapshot format version
       * @example 1
       */
      version: number
      /** @description Scene items (furniture, panels, etc.) */
      items: components['schemas']['SceneItem'][]
      /** @description Item groups */
      groups: components['schemas']['SceneGroup'][]
    }
    /** @description Opaque scene item — shape defined by frontend SceneItem type */
    SceneItem: {
      [key: string]: unknown
    }
    /** @description Opaque scene group — shape defined by frontend SceneGroup type */
    SceneGroup: {
      [key: string]: unknown
    }
    ErrorResponse: {
      /** @description Human-readable error message */
      message: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  GetHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  ListScenes: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of scenes */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SceneSummary'][]
        }
      }
    }
  }
  CreateScene: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SceneInput']
      }
    }
    responses: {
      /** @description Scene created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Scene']
        }
      }
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  GetScene: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Scene found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Scene']
        }
      }
      /** @description Scene not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  UpdateScene: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SceneInput']
      }
    }
    responses: {
      /** @description Scene updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Scene']
        }
      }
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Scene not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  DeleteScene: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Scene deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Scene not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
