// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"time"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Human-readable error message
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Scene defines model for Scene.
type Scene struct {
	CreatedAt time.Time `json:"createdAt"`

	// Data Scene content as stored by the frontend
	Data SceneData `json:"data"`

	// Id Unique identifier (UUID)
	Id string `json:"id"`

	// Name Human-readable scene name
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// SceneData Scene content as stored by the frontend
type SceneData struct {
	// Groups Item groups
	Groups []SceneGroup `json:"groups"`

	// Items Scene items (furniture, panels, etc.)
	Items []SceneItem `json:"items"`

	// Version Snapshot format version
	Version int `json:"version"`
}

// SceneGroup Opaque scene group — shape defined by frontend SceneGroup type
type SceneGroup map[string]interface{}

// SceneInput defines model for SceneInput.
type SceneInput struct {
	// Data Scene content as stored by the frontend
	Data SceneData `json:"data"`

	// Name Human-readable scene name
	Name string `json:"name"`
}

// SceneItem Opaque scene item — shape defined by frontend SceneItem type
type SceneItem map[string]interface{}

// SceneSummary defines model for SceneSummary.
type SceneSummary struct {
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier (UUID)
	Id string `json:"id"`

	// Name Human-readable scene name
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// CreateSceneJSONRequestBody defines body for CreateScene for application/json ContentType.
type CreateSceneJSONRequestBody = SceneInput

// UpdateSceneJSONRequestBody defines body for UpdateScene for application/json ContentType.
type UpdateSceneJSONRequestBody = SceneInput
